theme = "gruvbox-material"

[editor]
line-number = "relative"
auto-format = true
cursorline = true

path-completion = true
completion-trigger-len = 2

bufferline = "multiple"

clipboard-provider = "wayland"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["file-type", "diagnostics", "selections", "position", "file-encoding", "file-line-ending"]
separator = "│"
mode.normal = "普通"
mode.insert = "插入"
mode.select = "选择"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.inline-diagnostics]
other-lines = "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"S-k" = "page_up"
"S-j" = "page_down"
"S-up" = "page_up"
"S-down" = "page_down"
