theme = "everforest_dark"

[editor]
line-number = "relative"
auto-format = true
cursorline = true
popup-border = "popup"
color-modes = true
rainbow-brackets = true
default-yank-register = "+"

path-completion = true
completion-trigger-len = 2

bufferline = "multiple"

clipboard-provider = "wayland"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["file-type", "diagnostics", "position", "position-percentage", "file-encoding", "file-line-ending"]
separator = "│"
mode.normal = " "
mode.insert = " "
mode.select = " "
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[keys.normal]
"S-k" = "page_up"
"S-j" = "page_down"
"S-up" = "page_up"
"S-down" = "page_down"

[editor.word-completion]
trigger-length = 2
